export const listProductTypeSelector = (state) => state.getListProductTypeReducer.data
export const listProductGroupSelector = (state) => state.getListProductGroupReducer.data
export const messageCreateProductSelector = (state) => state.postCreateProductReducer.data
export const listProductSelector = (state) => state.getProductReducer.data
export const infoProductSelector = (state) => state.getInfoProductReducer.data
export const messageEditInfoProductSelector = (state) => state.postEditInfoProductReducer.data
export const mesAddProductDetailSelector = (state) => state.postAddProductDetailReducer.data
export const infoProductDetailSelector = (state) => state.getInfoProductDetailReducer.data
export const mesEditInfoProductDetailSelector = (state) => state.postEditInfoProductDetailReducer.data
export const infoProductSearchedSelector = (state) => state.getSearchProductReducer.data
export const infoMemberSearchedSelector = (state) => state.getSearchMemberReducer.data
export const mesAddMemberSelector = (state) => state.postAddMemberReducer.data